# Generated by Django 5.0.6 on 2024-05-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_is_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='photo',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_manager',
            field=models.BooleanField(default=False, verbose_name='Статус менеджера'),
        ),
    ]
