# Generated by Django 5.0.6 on 2024-05-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='employee_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Код сотрудника'),
        ),
    ]
