# Generated by Django 5.0.6 on 2024-05-20 21:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Refrigerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=200, verbose_name='Серийный номер')),
                ('model', models.CharField(max_length=200, verbose_name='Модель аппарата')),
                ('organization', models.TextField(blank=True, null=True, verbose_name='Организация расположения оборудования')),
                ('organization_address', models.TextField(blank=True, null=True, verbose_name='Адрес расположения организации')),
                ('is_assigned', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refrigerators', to=settings.AUTH_USER_MODEL, verbose_name='Закреплен за')),
            ],
            options={
                'verbose_name': 'Холодильник',
                'verbose_name_plural': 'Холодильники',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата и время отчета')),
                ('status', models.CharField(db_index=True, max_length=100, verbose_name='Статус отчета')),
                ('refrigerator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='report.refrigerator', verbose_name='Холодильник')),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/', verbose_name='Изображение')),
                ('comment_from', models.TextField(blank=True, null=True, verbose_name='Комментарий от торгового представителя')),
                ('comment_to', models.TextField(blank=True, null=True, verbose_name='Комментарий для торгового представителя')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='report.report', verbose_name='Отчет')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
            },
        ),
    ]
