# Generated by Django 5.0.6 on 2024-05-21 22:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название организации')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес организации')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='report_photos/', verbose_name='Фото отчета')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
            },
        ),
        migrations.CreateModel(
            name='Refrigerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=200, verbose_name='Серийный номер')),
                ('model', models.CharField(max_length=200, verbose_name='Модель аппарата')),
            ],
            options={
                'verbose_name': 'Холодильник',
                'verbose_name_plural': 'Холодильники',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата и время отчета')),
                ('status', models.CharField(choices=[('on_review', 'На рассмотрении'), ('approved', 'Одобрен'), ('decline', 'Отклонен')], db_index=True, max_length=100, verbose_name='Статус отчета')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий от торгового представителя')),
                ('comment_manager', models.TextField(blank=True, null=True, verbose_name='Комментарий от менеджера')),
                ('comment_admin', models.TextField(blank=True, null=True, verbose_name='Комментарий от админа')),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
            },
        ),
    ]
