# Generated by Django 5.0.6 on 2024-05-21 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('report', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='refrigerator',
            name='is_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refrigerators', to=settings.AUTH_USER_MODEL, verbose_name='Закреплен за'),
        ),
        migrations.AddField(
            model_name='refrigerator',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.organization', verbose_name='Организация расположения оборудования'),
        ),
        migrations.AddField(
            model_name='report',
            name='refrigerator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='report.refrigerator', verbose_name='Холодильник'),
        ),
        migrations.AddField(
            model_name='report',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='Отчет отправил'),
        ),
        migrations.AddField(
            model_name='photo',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='report.report', verbose_name='Отчет'),
        ),
    ]
