# Generated by Django 5.0.6 on 2024-05-28 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='manager_review',
            field=models.CharField(blank=True, choices=[('approve', 'Одобрено'), ('decline', 'Отклонено')], max_length=100, null=True, verbose_name='Рецензия менеджера'),
        ),
    ]
