# Generated by Django 5.0.6 on 2024-05-20 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_alter_refrigerator_is_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('on_review', 'На рассмотрении'), ('approved', 'Одобрен'), ('decline', 'Отклонен')], db_index=True, max_length=100, verbose_name='Статус отчета'),
        ),
    ]
