# Generated by Django 5.0.6 on 2024-11-14 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_report_manager_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-date'], 'verbose_name': 'Отчет', 'verbose_name_plural': 'Отчеты'},
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='report_photos/14.11.2024', verbose_name='Фото отчета'),
        ),
        migrations.AlterField(
            model_name='refrigerator',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='report.organization', verbose_name='Организация расположения оборудования'),
        ),
    ]
